---
apiVersion: v1
kind: Namespace
metadata:
  name: apache-drill
    
---
apiVersion: v1
kind: Service
metadata:
  name: apache-drill-headless-svc
  namespace: apache-drill
  labels:
    app: apache-drill-svc
spec:
  selector:
    app: apache-drill
  ports:
    - name: userport
      port: 31010
    - name: controlport
      port: 31011
    - name: dataport
      port: 31012
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: apache-drill-svc
  namespace: apache-drill
  labels:
    app: apache-drill-svc
spec:
  selector:
    app: apache-drill
  ports:
    - name: ui
      port: 8047

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget         
metadata:
  name: apache-drill-pdb
  namespace: apache-drill
spec:
  selector:
    matchLabels:
      app: apache-drill
  maxUnavailable: 1               # 1 POD off is acceptable for 3 node drill cluster


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apache-drill
  namespace: apache-drill
spec:
  selector:
    matchLabels:
      app: apache-drill
  replicas: 3
  serviceName: drill-headless-svc
  podManagementPolicy: OrderedReady               # default for StatefulSets
  template:
    metadata:
      labels:
        app: apache-drill
    spec:
      # affinity:
      #   podAntiAffinity:                                      # to avoid running multiple drill pods in same node (a HA practice)
      #     requiredDuringSchedulingIgnoredDuringExecution:     # scheduling pods based on labels that are already running on the node 
      #       - labelSelector:                                  # rather than based on labels on nodes    
      #           matchExpressions:                             # so we need 3 different nodes   
      #             - key: "app"                                # NOTE: Please un-comment this in production
      #               operator: In  
      #               values:
      #                 - apache-drill
      #         topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: zk-available
          image: busybox
          command: ["sh", "-c", "until nc -z zookeeper-svc.zookeeper.svc.cluster.local:2181; do echo 'Waiting for ZK cluster to UP'; done; "]
      containers:
        - name: apache-drill
          image: olishubham/apache-drill:1.15.0
          resources:
            requests:
              memory: "100Mi"                           # arbitrary resource limits
              cpu: "0.1"
          ports:
            - name: ui                              
              containerPort: 8047
            - name: userport
              containerPort: 31010
            - name: controlport
              containerPort: 31011
            - name: dataport
              containerPort: 31012
          readinessProbe:
            tcpSocket:
              port: ui
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: ui
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: ZK_SERVERS
              value: "zookeeper-svc.zookeeper.svc.cluster.local:2181"
          securityContext:
            runAsUser: 1000                         # set by image maintainer (https://github.com/shubhamoli/apache-drill-distributed)
